<?php

/**
 * @file
 * Contains flag_actions_foss.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function flag_actions_foss_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the flag_click_counter module.
    case 'help.page.flag_actions_foss':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Connects Flags to the FOSS API') . '</p>';
      return $output;

    default:
  }
}

